---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflareddns-config
  namespace: external-dns
data:
  PUID: '1000'
  PGID: '1000'
  UMASK: '002'
  TZ: Etc/UTC
  INTERNAL: '3000'
  DETECTION_MODE: dig-whoami.cloudflare
  LOG_LEVEL: '3'
  CF_HOSTS: luma.chrismiller.xyz;nightly.ipv8.dev;werethemille.rs;buttert.art;mc.realliance.net
  CF_ZONES:
    c5cc23ec906d72b94ae6789b946c95ac;81626617decf51cd013b8f578208e6b7;820af0c68573859bd1d0b6bd41185188;d8b2dca633086f6ea526c979b2082276;797612475ed6a8f7193a623ffc107f07
  CF_RECORDTYPES: A;A;A;A;A
